FROM nginx:alpine

COPY nginx.conf /etc/nginx/templates/default.conf.template

EXPOSE 8080

CMD sh -c 'sed "s/PORT_NUMBER/${PORT}/" /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
